### ISSUE TITLE
Can you make the address bar selected and empty?

### ISSUE THREAD

**Issue by mike-u** [startclean/Chrome-Extension#3]
Just as in the stock new tab, it's cumbersome right now to have to manually click and backspace the content in the address bar to type in a new website, or for googling something with the ol' super+(c-t-v)-enter.

**Comment by rawsh** [comment]
Right now the extension has a kind of hacky approach to this; what it does is go to a new tab start.html, then redirect to newtab.html so that the search box is focused. 

What I'm adding in the next version is an option whether to focus or not. If you choose not to focus the chrome address bar will be blank and focused.

**Comment by rawsh** [comment]
@mike-u check out the lite version of the extension, it was made with this issue in mind. There is no search box in that version. https://github.com/startclean/Chrome-Extension-Lite
